### PR TITLE
Increase maxPressure to survive Venus surface

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**
10500 kPa = 103.6 atm, enough to survive Venus surface (96 atm) plus a little extra.

h/t to @PhineasFreak: https://github.com/KSP-RO/RealismOverhaul/blob/68b29cf1b3c4a9bb0429bfa522fcbefa13f03459/GameData/RealismOverhaul/RO_SuggestedMods/CoatlAerospace/RO_CA_ProbesPlus_Command.cfg#L507

### CODE REVIEW

**Comment by raveloda** [comment]
I am going to close this here because it looks like it is being properly routed to the RO patch where the change is needed. I'd rather not merge this with the stock KSP version of Fomalhaut

**Comment by Kerbas-ad-astra** [comment]
Well, there are other systems besides RSS that have high pressures (and people who use RSS but not RO).  :/

**Comment by raveloda** [comment]
That makes sense. Let me re-visit this

**Comment by raveloda** [comment]
Reviewed. Merging changes

**Pull request merged**
